### ISSUE TITLE
  File "/usr/local/bin/multimanager", line 8, in <module>

### ISSUE THREAD

**Issue by vcan** [Spazzlo/folderclone#104]
when i run 'multimanager interactive'
get this error

`Traceback (most recent call last):
  File "/usr/local/bin/multimanager", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/folderclonecli/mmparse.py", line 272, in main
    import readline
ImportError: dlopen(/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so
  Reason: image not found`

**Comment by vcan** [comment]
This problem has been solved.
Upgrade Python3 to the latest version.
