### ISSUE TITLE
error executing multimanager interactive

### ISSUE THREAD

**Issue by daveraver** [Spazzlo/folderclone#110]
Hi to all! I got this message when I run multimanager interactive inside credentials folder:
~# multimanager interactive
Traceback (most recent call last):
  File "/usr/local/bin/multimanager", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/folderclonecli/mmparse.py", line 180, in main
    subparsers = parse.add_subparsers(help='Commands',dest='command',required=True)
  File "/usr/lib/python2.7/argparse.py", line 1674, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

How to fix these 3 errors? I dont know if some previous instalation (pip install folderclone and requirements) has been done wrong...

I am using a fresh debian 9 server instalation,

thanks in advance!

**Comment by daveraver** [comment]
I am sorry, by installing anaconda3 OS, I got it. After activate the base directory, multimanager interactive runs and I have been able to run muti manager mm> console

I am following the rest of the process, awaiting success.
Regards,
David
