### ISSUE TITLE
multimanager issues

### ISSUE THREAD

**Issue by ashagg1976** [Spazzlo/folderclone#122]
CentOS 7 x64. Python 3.6

pip3 install folderclone
multimanager interactive

# multimanager interactive
Traceback (most recent call last):
  File "/usr/local/bin/multimanager", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/folderclonecli/mmparse.py", line 180, in main
    subparsers = parse.add_subparsers(help='Commands',dest='command',required=True)
  File "/usr/local/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

**Comment by kngkngtian** [comment]
I got it on centOS 7 python3.6 too,did you resolve it?

**Comment by Spazzlo** [comment]
try updating python or something idk
