### ISSUE TITLE
Can't start new thread

### ISSUE THREAD

**Issue by microtechton** [Spazzlo/folderclone#130]
I'm receiving the error "Can't start new thread" when copying 2921 files
OS: Windows 10 Education x64
RAM: 16GB
Python Version: Python 3.8.3 32-bit

The following is the output:
```
can't start new thread
Exception in thread Thread-194:
Traceback (most recent call last):
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-324:
Traceback (most recent call last):
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-227:
Exception in thread Thread-181:
Traceback (most recent call last):
Traceback (most recent call last):
    self.run()
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 870, in run
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 171, in _copy
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self.run()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 171, in _copy
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 870, in run
Exception in thread Thread-328:
    self.run()
Traceback (most recent call last):
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 932, in _bootstrap_inner
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 870, in run
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
    self._target(*self._args, **self._kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 109, in _apicall
    self.run()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 171, in _copy
    self._target(*self._args, **self._kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\threading.py", line 870, in run
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 109, in _apicall
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
    resp = request.execute()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 171, in _copy
    resp = request.execute()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    self._target(*self._args, **self._kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 171, in _copy
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 109, in _apicall
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
    return wrapped(*args, **kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 892, in execute
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 109, in _apicall
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\folderclone\multifolderclone.py", line 109, in _apicall
    return wrapped(*args, **kwargs)
    resp = request.execute()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    resp = request.execute()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
    resp = request.execute()
    return wrapped(*args, **kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 892, in execute
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 892, in execute
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 892, in execute
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 892, in execute
    resp, content = _retry_request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = _retry_request(
    resp, content = _retry_request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = _retry_request(
    resp, content = _retry_request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
    resp, content = http.request(uri, method, *args, **kwargs)
    resp, content = http.request(uri, method, *args, **kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 186, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 197, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 197, in request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 186, in request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 197, in request
    response, content = self.http.request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1985, in request
    self.credentials.before_request(
    self.credentials.before_request(
    response, content = self.http.request(
    response, content = self.http.request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\auth\credentials.py", line 124, in before_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\auth\credentials.py", line 124, in before_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1985, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1985, in request
    (response, content) = self._request(
    (response, content) = self._request(
    self.refresh(request)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1650, in _request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1650, in _request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\oauth2\service_account.py", line 334, in refresh
    (response, content) = self._request(
    (response, content) = self._conn_request(
    (response, content) = self._conn_request(
    self.refresh(request)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1650, in _request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
    (response, content) = self._conn_request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
    raise _map_exception(e)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\oauth2\service_account.py", line 334, in refresh
    raise _map_exception(e)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 140, in _conn_request
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
    raise _map_exception(e)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 140, in _conn_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\oauth2\_client.py", line 153, in jwt_grant
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 140, in _conn_request
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
    urllib3_response = self.pool.request(
    urllib3_response = self.pool.request(
    urllib3_response = self.pool.request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\oauth2\_client.py", line 153, in jwt_grant
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 79, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 79, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 79, in request
    response_data = _token_endpoint_request(request, token_uri, body)
    response_data = _token_endpoint_request(request, token_uri, body)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\oauth2\_client.py", line 105, in _token_endpoint_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google\oauth2\_client.py", line 105, in _token_endpoint_request
    return self.request_encode_body(
    return self.request_encode_body(
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 115, in __call__
    response = request(method="POST", url=token_uri, headers=headers, body=body)
    return self.request_encode_body(
    return self.urlopen(method, url, **extra_kw)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\google_auth_httplib2.py", line 115, in __call__
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response, data = self.http.request(
    return self.urlopen(method, url, **extra_kw)
    response, data = self.http.request(
    return self.urlopen(method, url, **extra_kw)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1985, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1985, in request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    (response, content) = self._request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1650, in _request
    (response, content) = self._request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2\__init__.py", line 1650, in _request
    (response, content) = self._conn_request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
    response = conn.urlopen(method, u.request_uri, **kw)
    response = conn.urlopen(method, u.request_uri, **kw)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\connectionpool.py", line 690, in urlopen
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\connectionpool.py", line 690, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
    raise _map_exception(e)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\connectionpool.py", line 690, in urlopen
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 140, in _conn_request
    (response, content) = self._conn_request(
    urllib3_response = self.pool.request(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 79, in request
    raise _map_exception(e)
    return self.request_encode_body(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\httplib2shim\__init__.py", line 140, in _conn_request
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    urllib3_response = self.pool.request(
    return self.urlopen(method, url, **extra_kw)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 79, in request
    response = self.ResponseCls.from_httplib(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = self.ResponseCls.from_httplib(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 601, in from_httplib
    return self.request_encode_body(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 601, in from_httplib
    response = conn.urlopen(method, u.request_uri, **kw)
    response = self.ResponseCls.from_httplib(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\connectionpool.py", line 690, in urlopen
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 601, in from_httplib
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    response = self.ResponseCls.from_httplib(
    return self.urlopen(method, url, **extra_kw)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 601, in from_httplib
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\connectionpool.py", line 690, in urlopen
    response = self.ResponseCls.from_httplib(
    resp = ResponseCls(
    resp = ResponseCls(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 601, in from_httplib
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 259, in __init__
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 259, in __init__
    resp = ResponseCls(
    resp = ResponseCls(
    resp = ResponseCls(
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 259, in __init__
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 259, in __init__
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 259, in __init__
    self._body = self.read(decode_content=decode_content)
    self._body = self.read(decode_content=decode_content)
    self._body = self.read(decode_content=decode_content)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 548, in read
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 548, in read
    self._body = self.read(decode_content=decode_content)
    self._body = self.read(decode_content=decode_content)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 548, in read
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 548, in read
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 548, in read
    data = self._decode(data, decode_content, flush_decoder)
    data = self._decode(data, decode_content, flush_decoder)
    data = self._decode(data, decode_content, flush_decoder)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 409, in _decode
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 409, in _decode
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 409, in _decode
    data = self._decode(data, decode_content, flush_decoder)
    data = self._decode(data, decode_content, flush_decoder)
    data += self._flush_decoder()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 400, in _decode
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 400, in _decode
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 420, in _flush_decoder
    data += self._flush_decoder()
    data += self._flush_decoder()
    data = self._decoder.decompress(data)
    data = self._decoder.decompress(data)
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 420, in _flush_decoder
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 86, in decompress
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 86, in decompress
    return buf + self._decoder.flush()
  File "d:\applications\program files (x86)\python38-32\lib\site-packages\urllib3\response.py", line 420, in _flush_decoder
    return buf + self._decoder.flush()
MemoryError
    ret += self._obj.decompress(data)
MemoryError
    return buf + self._decoder.flush()
    ret += self._obj.decompress(data)
MemoryError
MemoryError
MemoryError
```

**Comment by JoseAngelB** [comment]
I have another output for the "same" error:
`'charmap' codec can't encode characters in position 0-2: character maps to <undefined>`
I think it happens _after_ copy a file with a UTF-8 character. The file is copied and the error comes after that, if you run the same command again it doesn't happen because the file isn't copied

**Comment by Spazzlo** [comment]
i didn't know there was a windows 10 educational edition. try getting more ram.
