### ISSUE TITLE
EDU account, The user's Drive storage quota has been exceeded.

### ISSUE THREAD

**Issue by ekeroseprod** [Spazzlo/folderclone#58]
Hi.
After download and configure new script version (20191001) and creating fresh proyect and accounts when copiing from a TeamDrive to a personal unlimited account shows an error of quota exceeded

Exception in thread Thread-3:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1QCZQ6pIJiAE1fU4CGMhOeeGZV74tCISK/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1PXs_NFctBVciLbFOHn91mEgFtdRXyirX/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1aTPIkwY2Su-1yV7DQV022mEqE80Dbhvl/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'
Exception in thread Thread-11:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1SI1cFj4GVngw6d4eIe9o2I1WJr2FyXqr/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-9:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1Xk0wGFSbapm2654eXSukAUiZhSorJTtV/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-10:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1lTZ6gN2WujlzQbGHvCJ1Vezwz34Xu8JV/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1cC05k4oBvHWj4UOE-PihKfDhauetF6xW/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'
Exception in thread Thread-12:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1If2vBtyzKrbkAxat9Awj3UZ5Erq0u5Jo/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

│   ├── Bajo Escucha (The Wire) | Synced
Exception in thread Thread-18:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1SVKz2RPVt5lxRuFAcXeJTh_BqXlrEjx5/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-14:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1CVcnXwUzbeFGF6AyKTO1_5cWjJdyVPik/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-35:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1_QWltXrNTwbpRvg36o09XwGDphVlyqSK/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-36:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1THrJqEiFupoVg-4C4_dMZyxb_Q5MVvfe/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-34:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1fSct1LcDBMJy71tF2qx86HAEJLyS2Qt-/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-32:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1psY69xHhrE1nf9bEmlEWc55jMhdUCW3m/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-26:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1jfw4i8d5eT-_L9UKRA8fOrdJuAmFRZEq/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-30:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/10A7y-j8IWXDKyPHPzR3sDBpHewh1fXSC/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-31:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1qogutREt094gYEVQATufIMcGxINKgF0w/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-28:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/14nAm6x73I3f_CxoeX3l-7EYcuce2quIz/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-42:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1GqWx1GaFZZkWghzstL9HJNDx8SRgJsoM/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-50:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1zKxvKVovRIPcCy4RpHsJd-_bcPDF2wFy/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-49:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/10I2Iok69-WpjtdQlaQkri223oASsuUPM/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-41:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1z2YAD6K2_QEmEdATtVg1Z2ZWsTDlFTnI/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-52:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1iocdYwI89ImnOSQRVLnnbDYc-PdD28Pq/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'storageQuotaExceeded'

Exception in thread Thread-43:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Albert\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/12_xTRAsjK-YWMhE8GMGueUIH_we7uCFA/copy?supportsAllDrives=true&alt=json returned "The user's Drive storage quota has been exceeded.">

During handling of the above exception, another exception occurred:

**Comment by Mz49** [comment]
You skipped the part that you have to use a Shared Drive. Copying directly to a user's Drive will **NOT** work.

**Comment by ekeroseprod** [comment]
Previous version works with a shared folder inside a personal drive putting
manually the accounts as managers, was lost this functionality?

**Comment by Mz49** [comment]
@ekeroseprod That functionality never existed. You were probably got lucky somehow.

**Comment by ekeroseprod** [comment]
I followed Blackpearl's guides and it was working, but one day it started
to freeze and luck ended.

**Comment by Mz49** [comment]
@ekeroseprod That functionality never existed. You were probably got lucky somehow.
