### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by yuritry** [Spazzlo/folderclone#62]
Traceback (most recent call last):
  File "multifolderclone.py", line 301, in <module>
    main()
  File "multifolderclone.py", line 297, in main
    thread_count=args.threads
  File "multifolderclone.py", line 270, in multifolderclone
    rcopy(drive, 1, source, dest, root_dir, "", width)
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  [Previous line repeated 2 more times]
  File "multifolderclone.py", line 130, in rcopy
    files_source = lsf(source)
  File "multifolderclone.py", line 113, in lsf
    searchTerms=" and not mimeType contains 'application/vnd.google-apps.folder'"
  File "multifolderclone.py", line 88, in ls
    files += resp["files"]
TypeError: 'bool' object is not subscriptable

Traceback (most recent call last):
  File "multifolderclone.py", line 301, in <module>
    main()
  File "multifolderclone.py", line 297, in main
    thread_count=args.threads
  File "multifolderclone.py", line 270, in multifolderclone
    rcopy(drive, 1, source, dest, root_dir, "", width)
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  [Previous line repeated 3 more times]
  File "multifolderclone.py", line 132, in rcopy
    folders_source = lsd(source)
  File "multifolderclone.py", line 107, in lsd
    searchTerms=" and mimeType contains 'application/vnd.google-apps.folder'"
  File "multifolderclone.py", line 88, in ls
    files += resp["files"]
TypeError: 'bool' object is not subscriptable

**Comment by Mz49** [comment]
Very strange error you've got there. We'll look into it.

**Comment by yuritry** [comment]
Traceback (most recent call last):
  File "multifolderclone.py", line 301, in <module>
    main()
  File "multifolderclone.py", line 297, in main
    thread_count=args.threads
  File "multifolderclone.py", line 270, in multifolderclone
    rcopy(drive, 1, source, dest, root_dir, "", width)
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  [Previous line repeated 2 more times]
  File "multifolderclone.py", line 158, in rcopy
    drive[dtu],
IndexError: list index out of range

**Comment by yuritry** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Program Files\Python37\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\httplib2shim\__init__.py", line 148, in _conn_request
    decode_content=decode)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Program Files\Python37\lib\site-packages\urllib3\request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Python37\lib\site-packages\urllib3\util\retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001CF9FD31808>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multifolderclone.py", line 301, in <module>
    main()
  File "multifolderclone.py", line 297, in main
    thread_count=args.threads
  File "multifolderclone.py", line 240, in multifolderclone
    check = build("drive", "v3", credentials=Credentials.from_service_account_file(accounts[0]))
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\discovery.py", line 223, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\discovery.py", line 273, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Program Files\Python37\lib\site-packages\httplib2\__init__.py", line 1957, in request
    cachekey,
  File "C:\Program Files\Python37\lib\site-packages\httplib2\__init__.py", line 1622, in _request
    conn, request_uri, method, body, headers
  File "C:\Program Files\Python37\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
    raise _map_exception(e)
socket.timeout: timed out

**Comment by Mz49** [comment]
@yuritry Do you think you can run this with the `--debug-mode` flag? It'll print some stuff I left in there that could very useful for me to debug this issue.

**Comment by yuritry** [comment]
OK

**Comment by yuritry** [comment]
Exception in thread Thread-145699:
Traceback (most recent call last):
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting  returned "The file limit for this shared drive has been exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 65, in apicall
    elif error_codes[reason]:
KeyError: 'teamDriveFileLimitExceeded'

**Comment by Mz49** [comment]
Well, that's a new error. Will add handling of it. Still looking in the the IndexError. Thanks for the error log.

**Comment by eXhumer** [comment]
'teamDriveFileLimitExceeded' - Max file limit for that shared error. We can't do anything about that. Use a different one.

**Comment by eXhumer** [comment]
@Mz49 - I'll look into adding error handling for that, unless you prefer to do it yourself.

**Comment by eXhumer** [comment]
That dtu out of index is also avoidable if you add an if check before trying drive[dtu]

**Comment by yuritry** [comment]
teamDriveFileLimitExceeded : too many files.  Too many small files is a problem.

**Comment by eXhumer** [comment]
No. Team Drives has a maximum size of 400,000 files.

**Comment by eXhumer** [comment]
You get that error when you try to exceed that.

**Comment by yuritry** [comment]
400,000 per day, or totally?

**Comment by eXhumer** [comment]
https://support.google.com/a/answer/7338880?hl=en

Per Shared Drive.

**Comment by yuritry** [comment]
I see. Thank you.
And how many shared drives could I make?  Does Google charge for that?

**Comment by Mz49** [comment]
That is info you can fin by yourself on Google.

https://support.google.com/a/answer/7212025?hl=en

**Comment by yuritry** [comment]
Traceback (most recent call last):
  File "multifolderclone.py", line 301, in <module>
    main()
  File "multifolderclone.py", line 297, in main
    thread_count=args.threads
  File "multifolderclone.py", line 270, in multifolderclone
    rcopy(drive, 1, source, dest, root_dir, "", width)
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  [Previous line repeated 8 more times]
  File "multifolderclone.py", line 130, in rcopy
    files_source = lsf(source)
  File "multifolderclone.py", line 113, in lsf
    searchTerms=" and not mimeType contains 'application/vnd.google-apps.folder'"
  File "multifolderclone.py", line 88, in ls
    files += resp["files"]
TypeError: 'bool' object is not subscriptable

**Comment by yuritry** [comment]
Thank you.

**Comment by yuritry** [comment]
<HttpError 403 when requesting https://www.googleapis.com/drive/v3/files?q returned "User rate limit exceeded.">
 
But only about 10T and 100 users.

**Comment by Mz49** [comment]
Where are you getting that issue?

**Comment by yuritry** [comment]
<HttpError 403 when requesting https://www.googleapis.com/drive/v3/files?q=%270ByWO0aO1eI_MQ09fV28xS0xUZEE%27+in+parents+and+mimeType+contains+%27application%2Fvnd.google-apps.folder%27&fields=files%28md5Checksum%2Cid%2Cname%29%2CnextPageToken&pageSize=1000&supportsAllDrives=true&includeItemsFromAllDrives=true&alt=json returned "User rate limit exceeded.">
Traceback (most recent call last):
  File "multifolderclone.py", line 301, in <module>
    main()
  File "multifolderclone.py", line 297, in main
    thread_count=args.threads
  File "multifolderclone.py", line 270, in multifolderclone
    rcopy(drive, 1, source, dest, root_dir, "", width)
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  File "multifolderclone.py", line 227, in rcopy
    width
  [Previous line repeated 6 more times]
  File "multifolderclone.py", line 132, in rcopy
    folders_source = lsd(source)
  File "multifolderclone.py", line 107, in lsd
    searchTerms=" and mimeType contains 'application/vnd.google-apps.folder'"
  File "multifolderclone.py", line 88, in ls
    files += resp["files"]
TypeError: 'bool' object is not subscriptable

**Comment by yuritry** [comment]
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

**Comment by yuritry** [comment]
I think it may because I did several times to the same shared drive with the same users.
I have 100 users for the shared drive.  There may be one of them that exceeded the Daily Limit.

**Comment by eXhumer** [comment]
I believe that error is due to having one of the required API disabled.

**Comment by eXhumer** [comment]
Make sure you have Drive API and IAM API enabled.

**Comment by yuritry** [comment]
They are enabled.
The error happened after several T was transferred.

**Comment by Mz49** [comment]
@yuritry I believe the new push addresses the IndexError, not sure about the 'bool' object is not subscriptable error. Care to give the new one a try?

**Comment by yuritry** [comment]
Ok

**Comment by czahoi** [comment]
'bool' object is not subscriptable    occur       no reach google api limits

**Comment by Sirfrancis17** [comment]
I have the same problem
List index out of range
Mi shared drive has 60000 files
