### ISSUE TITLE
google.auth.exceptions.TransportError: unable to find hostname

### ISSUE THREAD

**Issue by BignThicc** [Spazzlo/folderclone#65]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "multifolderclone.py", line 119, in copy
    if apicall(driv.files().copy(fileId=source, body={"parents": [dest]}, supportsAllDrives=True)) == False:
  File "multifolderclone.py", line 52, in apicall
    resp = request.execute()
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/googleapiclient/http.py", line 165, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/Users/bignthicc/.virtualenvs/ccsfclone/lib/python3.7/site-packages/google_auth_httplib2.py", line 119, in __call__
    raise exceptions.TransportError(exc)
google.auth.exceptions.TransportError: Unable to find hostname.

**Comment by Mz49** [comment]
@eXhumer Do you think you can add some more error handling?

**Comment by eXhumer** [comment]
Sure. I'll look into it in a bit and see what I can do about it.

**Comment by kichetof** [comment]
Hi guys,
some other errors with `unable to find hostname` on macOS Catalina, python 3.7.2 with pyenv and multifolderclone 0.5.3 _(same error with 0.5.3beta)_.

```
Traceback (most recent call last):
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/httplib2shim/__init__.py", line 148, in _conn_request
    decode_content=decode)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x114697dd8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/folderclone/multifolderclone.py", line 171, in _copy
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/folderclone/multifolderclone.py", line 109, in _apicall
    resp = request.execute()
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/googleapiclient/http.py", line 184, in _retry_request
    raise exception
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/googleapiclient/http.py", line 165, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/httplib2/__init__.py", line 1957, in request
    cachekey,
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/httplib2/__init__.py", line 1622, in _request
    conn, request_uri, method, body, headers
  File "/Users/tof/.pyenv/versions/3.7.2/lib/python3.7/site-packages/httplib2shim/__init__.py", line 154, in _conn_request
    raise _map_exception(e)
httplib2.ServerNotFoundError: Unable to find hostname.
```

Only solution is to kill the command every time and relaunched it.
Hope that could help you to resolve it :)

**Comment by kichetof** [comment]
Little update. When I add `--verbose` flag, everything run well! Slowly, but without any error!

**Comment by thekiefs** [comment]
I am getting similar errors, even with the `--verbose `flag:

```
Exception in thread Thread-4948:
Traceback (most recent call last):
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/httplib2shim/__init__.py", line 148, in _conn_request
    decode_content=decode)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x109e9bf10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/folderclone/multifolderclone.py", line 171, in _copy
    if self._apicall(driv.files().copy(fileId=source, body={'parents': [dest]}, supportsAllDrives=True)) == False:
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/folderclone/multifolderclone.py", line 109, in _apicall
    resp = request.execute()
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/googleapiclient/http.py", line 901, in execute
    headers=self.headers,
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/Users/thekiefs/.pyenv/versions/3.7.7/lib/python3.7/site-packages/httplib2shim/__init__.py", line 154, in _conn_request
    raise _map_exception(e)
httplib2.ServerNotFoundError: Unable to find hostname.
```
