### ISSUE TITLE
UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by trans2014** [Spazzlo/folderclone#71]
Getting this error when trying to run multimanager interactive in the folder where I have put credentials.json. I have the newest python, installed folderclone through pip and the requirements.

D:\scripts>multimanager interactive
Please visit this URL to authorize this application: https:/ /accounts.google.com/o/oauth2/auth?response_type=code&client_id=**hereismyclientid**&redirect_uri=http%3A%2F%2Flocalhost%3A53943%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam&state=uYYrIrcVCzemHxMpAOG7h8C8arRkYh&access_type=offline&code_challenge=_2hGWebPS9DFEN7ClWAXDcNuhcLJ_1EDE8CE_NQVhXs&code_challenge_method=S256
Traceback (most recent call last):
  File "c:\users\<<user>>\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\<<user>>\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<<user>>\AppData\Local\Programs\Python\Python37\Scripts\multimanager.exe\__main__.py", line 9, in <module>
  File "c:\users\<<user>>\appdata\local\programs\python\python37\lib\site-packages\folderclonecli\mmparse.py", line 262, in main
    max_projects=args.max_projects
  File "c:\users\<<user>>\appdata\local\programs\python\python37\lib\site-packages\folderclone\multimanager.py", line 112, in __init__
    sas = self.list_service_accounts(self.proj_id)
  File "c:\users\<<user>>\appdata\local\programs\python\python37\lib\site-packages\folderclone\multimanager.py", line 146, in list_service_accounts
    if 'accounts' in resp:
UnboundLocalError: local variable 'resp' referenced before assignment

**Comment by Mz49** [comment]
Thank you for the error. It is now fixed.
