### ISSUE TITLE
issue with “multimanager interactive"

### ISSUE THREAD

**Issue by yuritry** [Spazzlo/folderclone#83]
when I ran "multimanager interactive", showing following error:

Traceback (most recent call last):
  File "c:\progra~1\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\progra~1\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\multimanager.exe\__main__.py", line 9, in <module>
  File "c:\progra~1\python37\lib\site-packages\folderclonecli\mmparse.py", line 265, in main
    max_projects=args.max_projects
  File "c:\progra~1\python37\lib\site-packages\folderclone\multimanager.py", line 83, in __init__
    self.usage_service = self._build_service('serviceusage','v1')
  File "c:\progra~1\python37\lib\site-packages\folderclone\multimanager.py", line 71, in _build_service
    'https://www.googleapis.com/auth/iam'])
  File "c:\progra~1\python37\lib\site-packages\folderclone\_helpers.py", line 20, in get_creds
    flow = InstalledAppFlow.from_client_secrets_file(credentials,scopes)
  File "c:\progra~1\python37\lib\site-packages\google_auth_oauthlib\flow.py", line 199, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)
  File "c:\progra~1\python37\lib\site-packages\google_auth_oauthlib\flow.py", line 159, in from_client_config
    'Client secrets must be for a web or installed app.')
ValueError: Client secrets must be for a web or installed app.

**Comment by JackInTheShop** [comment]
You probably did not download the correct credentials or did not set them up correctly. Try the README again. @Spazzlo I think it would be a good idea to handle this error, regardless.

**Comment by yuritry** [comment]
I used the wrong project.
