### ISSUE TITLE
连不上。谢谢

### ISSUE THREAD

**Issue by saysee** [Spazzlo/folderclone#84]
共享文件拷贝到团队盘，显示如下：

Traceback (most recent call last):
  File "multifolderclone.py", line 114, in <module>
    drive.append(googleapiclient.discovery.build("drive", "v3", credentials=credentials))
  File "C:\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Programs\Python\Python37\lib\site-packages\googleapiclient\discovery.py", line 223, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "C:\Programs\Python\Python37\lib\site-packages\googleapiclient\discovery.py", line 273, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Programs\Python\Python37\lib\site-packages\httplib2\__init__.py", line 1957, in request
    cachekey,
  File "C:\Programs\Python\Python37\lib\site-packages\httplib2\__init__.py", line 1622, in _request
    conn, request_uri, method, body, headers
  File "C:\Programs\Python\Python37\lib\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
    raise _map_exception(e)
socket.timeout: timed out

**Comment by Spazzlo** [comment]
that ain't good

**Comment by WithdrawnObserver** [comment]
SSTAP全局

**Comment by iostream-cute** [comment]
sockscap64 强制cmd走代理
