### ISSUE TITLE
Error while executing multimanager interactive

### ISSUE THREAD

**Issue by Rajwadkar07** [Spazzlo/folderclone#85]
This is what I get after executing "multimanager interactive" 
`Traceback (most recent call last):
  File "/home/shadystoneboi/.local/bin/multimanager", line 11, in <module>
    sys.exit(main())
  File "/home/shadystoneboi/.local/lib/python3.6/site-packages/folderclonecli/mmparse.py", line 180, in main
    subparsers = parse.add_subparsers(help='Commands',dest='command',required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'`

**Comment by JackInTheShop** [comment]
I had a hard time with that as well. You will need to update to python 3.7 to run multimanager.

**Comment by Rajwadkar07** [comment]
Updated Python to 3.7 yet the same error

**Comment by quorn23** [comment]
I'm facing the same error. 
No matter if i install folderclone and the requirements with pip or pip3, the error remains the same
python3.7 --version:
Python 3.7.6

any help would be very appreciated
